# This file needs to be next to the shinyproxy-1.0.2.jar. We then launch
# shinyproxy like so:
#
#     $ java -jar shinyproxy-1.0.2.jar &
shiny:
  proxy:
    title: Denali Therapeutics
    logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
    landing-page: /
    container-wait-time: 20000
    heartbeat-rate: 10000
    heartbeat-timeout: 60000
    port: 8080
    authentication: none
    #authentication: ldap
    #admin-groups: scientists
    # Example: 'ldap' authentication configuration, see note below
    #ldap:
    #  url: ldap://ldap.forumsys.com:389/dc=example,dc=com
    #  user-dn-pattern: uid={0}
    #  group-search-base:
    #  group-search-filter: (uniqueMember={0})
    #  manager-dn: cn=read-only-admin,dc=example,dc=com
    #  manager-password: password
    # Docker configuration
    # You have to ensure that your docker daemon is listening to port 2375.
    # How you configure this is distribution-dependent.
    docker:
      cert-path: /home/none
      url: http://localhost:2375
      port-range-start: 20000
  apps:
  - name: multiGSEA
    display-name: multiGSEA Explorer
    description: Application that enables interactive exploration of GSEA results.
    docker-cmd: ["R", "-e", "multiGSEA.shiny::explore()"]
    docker-image: lianos/multigsea-shinyproxy
    #groups: scientists, mathematicians
logging:
  file:
    shinyproxy.log

# Using test LDAP server:
# https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/
#
# groups: one or more groups (e.g. LDAP groups) a user needs to belong to in
#         order to gain access to the app; this field allows to authorize access
#         per app; to test the authorization with LDAP authentication, one can
#         use gauss with password password as an example mathematician; user
#         tesla with password password is one of the example scientists. Other
#         users are described in link above.
#
# Apps for which `groups` are not specified are treated as "public", which is
# to say that all authenticated users can access.
